modLoader="javafml"
loaderVersion="[32,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/PumpkinPotions/issues"

[[mods]]
modId="pumpkinpotions"
version="${file.jarVersion}"
displayName="PumpkinPotions"
displayURL="http://placeholder.invalid"
authors="noeppi_noeppi"
description='''
Brew complex potions in a pumpkin
'''

[[dependencies.pumpkinpotions]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pumpkinpotions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"