modLoader="javafml"
loaderVersion="[32,)"
license="APACHE-2.0"
issueTrackerURL="http://placeholder.invalid"

[[mods]]
modId="pumpkinpotions"
version="${file.jarVersion}"
displayName="PumpkinPotions"
displayURL="http://placeholder.invalid"
authors="noeppi_noeppi"
description='''
Dive deeper into the world of botania.
'''

[[dependencies.pumpkinpotions]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pumpkinpotions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"