package pumpkinpotions.brew;

import com.google.common.collect.ImmutableMap;
import net.minecraft.item.Item;
import net.minecraft.item.Items;

import java.util.Map;

import static pumpkinpotions.brew.ItemAffinities.*;
import static pumpkinpotions.brew.Affinity.*;

public class ItemBrew {

    public static final Map<Item, ItemAffinities> EFFECT_DATA = ImmutableMap.<Item, ItemAffinities>builder()
            /*.put(Items.STONE, negligible(MINE, LANDSCAPE, CAVE))
            .put(Items.GRANITE, negligible(MINE, HELL))
            .put(Items.POLISHED_GRANITE, negligible(CRAFT, HELL))
            .put(Items.DIORITE, negligible(MINE, COLD))
            .put(Items.POLISHED_DIORITE, negligible(CRAFT, COLD))
            .put(Items.ANDESITE, negligible(MINE, TRASH))
            .put(Items.POLISHED_ANDESITE, negligible(CRAFT, TRASH))
            .put(Items.GRASS_BLOCK, weak(LANDSCAPE, EARTH, WET))
            .put(Items.DIRT, negligible(EARTH, LANDSCAPE, DRY))
            .put(Items.COARSE_DIRT, negligible(EARTH, DRY, TRASH))
            .put(Items.PODZOL, weak(LANDSCAPE, EARTH, DRY))
            .put(Items.CRIMSON_NYLIUM, weak(HELL, POWER))
            .put(Items.WARPED_NYLIUM, weak(HELL, WEAK))
            .put(Items.COBBLESTONE, negligible(TRASH, MINE))
            .put(Items.OAK_PLANKS, negligible(EARTH, LANDSCAPE, CAVE))
            .put(Items.BIRCH_PLANKS, negligible(EARTH, LANDSCAPE, TRASH))
            .put(Items.SPRUCE_PLANKS, negligible(EARTH, LANDSCAPE, COLD))
            .put(Items.JUNGLE_PLANKS, negligible(EARTH, LANDSCAPE, WET))
            .put(Items.ACACIA_PLANKS, negligible(EARTH, LANDSCAPE, HOT))
            .put(Items.DARK_OAK_PLANKS, negligible(EARTH, LANDSCAPE, DARK))
            .put(Items.CRIMSON_PLANKS, negligible(EARTH, LANDSCAPE, HELL))
            .put(Items.WARPED_PLANKS, negligible(EARTH, LANDSCAPE, END))
            .put(Items.SAND, negligible(DRY, HOT, LANDSCAPE))
            .put(Items.RED_SAND, negligible(HOT, DRY, LANDSCAPE))
            .put(Items.GRAVEL, negligible(CAVE, MINE, TRASH))
            .put(Items.GOLD_ORE, decent(TREASURE, MINE, CAVE))
            .put(Items.IRON_ORE, decent(MINE, CAVE))
            .put(Items.IRON_ORE, weak(MINE, CAVE))
            .put(Items.NETHER_GOLD_ORE, weak(HELL, LANDSCAPE, TREASURE))
            .put(Items.OAK_LOG, veryWeak(EARTH, LANDSCAPE, CAVE))
            .put(Items.BIRCH_LOG, veryWeak(EARTH, LANDSCAPE, TRASH))
            .put(Items.SPRUCE_LOG, veryWeak(EARTH, LANDSCAPE, COLD))
            .put(Items.JUNGLE_LOG, veryWeak(EARTH, LANDSCAPE, WET))
            .put(Items.ACACIA_LOG, veryWeak(EARTH, LANDSCAPE, HOT))
            .put(Items.DARK_OAK_LOG, veryWeak(EARTH, LANDSCAPE, DARK))
            .put(Items.CRIMSON_STEM, veryWeak(EARTH, LANDSCAPE, HELL))
            .put(Items.WARPED_STEM, veryWeak(EARTH, LANDSCAPE, END))
            .put(Items.STRIPPED_OAK_LOG, veryWeak(EARTH, LANDSCAPE, CAVE))
            .put(Items.STRIPPED_BIRCH_LOG, veryWeak(EARTH, LANDSCAPE, TRASH))
            .put(Items.STRIPPED_SPRUCE_LOG, veryWeak(EARTH, LANDSCAPE, COLD))
            .put(Items.STRIPPED_JUNGLE_LOG, veryWeak(EARTH, LANDSCAPE, WET))
            .put(Items.STRIPPED_ACACIA_LOG, veryWeak(EARTH, LANDSCAPE, HOT))
            .put(Items.STRIPPED_DARK_OAK_LOG, veryWeak(EARTH, LANDSCAPE, DARK))
            .put(Items.STRIPPED_CRIMSON_STEM, veryWeak(EARTH, LANDSCAPE, HELL))
            .put(Items.STRIPPED_WARPED_STEM, veryWeak(EARTH, LANDSCAPE, END))
            .put(Items.OAK_WOOD, veryWeak(EARTH, LANDSCAPE, CAVE))
            .put(Items.BIRCH_WOOD, veryWeak(EARTH, LANDSCAPE, TRASH))
            .put(Items.SPRUCE_WOOD, veryWeak(EARTH, LANDSCAPE, COLD))
            .put(Items.JUNGLE_WOOD, veryWeak(EARTH, LANDSCAPE, WET))
            .put(Items.ACACIA_WOOD, veryWeak(EARTH, LANDSCAPE, HOT))
            .put(Items.DARK_OAK_WOOD, veryWeak(EARTH, LANDSCAPE, DARK))
            .put(Items.CRIMSON_HYPHAE, veryWeak(EARTH, LANDSCAPE, HELL))
            .put(Items.WARPED_HYPHAE, veryWeak(EARTH, LANDSCAPE, END))
            .put(Items.STRIPPED_OAK_WOOD, veryWeak(EARTH, LANDSCAPE, CAVE))
            .put(Items.STRIPPED_BIRCH_WOOD, veryWeak(EARTH, LANDSCAPE, TRASH))
            .put(Items.STRIPPED_SPRUCE_WOOD, veryWeak(EARTH, LANDSCAPE, COLD))
            .put(Items.STRIPPED_JUNGLE_WOOD, veryWeak(EARTH, LANDSCAPE, WET))
            .put(Items.STRIPPED_ACACIA_WOOD, veryWeak(EARTH, LANDSCAPE, HOT))
            .put(Items.STRIPPED_DARK_OAK_WOOD, veryWeak(EARTH, LANDSCAPE, DARK))
            .put(Items.STRIPPED_CRIMSON_HYPHAE, veryWeak(EARTH, LANDSCAPE, HELL))
            .put(Items.STRIPPED_WARPED_HYPHAE, veryWeak(EARTH, LANDSCAPE, END))*/

            .put(Items.DRAGON_EGG, insane(POWER, END, TREASURE))
            .put(Items.NETHER_STAR, insane(POWER, HELL, HOT))
            .put(Items.SPONGE, strong(WATER))
            .put(Items.OAK_SAPLING, weak(EARTH, LANDSCAPE, CAVE))
            .put(Items.BIRCH_SAPLING, weak(EARTH, LANDSCAPE, TRASH))
            .put(Items.SPRUCE_SAPLING, weak(EARTH, LANDSCAPE, COLD))
            .put(Items.JUNGLE_SAPLING, weak(EARTH, LANDSCAPE, WET))
            .put(Items.ACACIA_SAPLING, weak(EARTH, LANDSCAPE, HOT))
            .put(Items.DARK_OAK_SAPLING, weak(EARTH, LANDSCAPE, DARK))
            .put(Items.GRASS, weak(LANDSCAPE, LIGHT))
            .put(Items.DEAD_BUSH, weak(DRY, HOT))
            .put(Items.SEAGRASS, weak(WET, COLD))
            .put(Items.SEA_PICKLE, weak(WATER, LIGHT))
            .put(Items.DANDELION, weak(CAVE, HOT, EARTH))
            .put(Items.POPPY, weak(CAVE, LIGHT, EARTH))
            .put(Items.BLUE_ORCHID, weak(LANDSCAPE, WET, EARTH))
            .put(Items.ALLIUM, weak(FIRE, HOT, EARTH))
            .put(Items.AZURE_BLUET, weak(DARK, END, EARTH))
            .put(Items.RED_TULIP, weak(WEAK, WATER, EARTH))
            .put(Items.ORANGE_TULIP, weak(WATER, WEAK, EARTH))
            .put(Items.PINK_TULIP, weak(WEAK, WATER, LANDSCAPE))
            .put(Items.WHITE_TULIP, weak(WATER, WEAK, LANDSCAPE))
            .put(Items.OXEYE_DAISY, weak(POWER, WET, EARTH))
            .put(Items.CORNFLOWER, weak(DRY, COLD, EARTH))
            .put(Items.LILY_OF_THE_VALLEY, weak(WEAK, DRY, EARTH))
            .put(Items.RED_MUSHROOM, normal(DARK, TRASH))
            .put(Items.BROWN_MUSHROOM, normal(DARK, TREASURE))
            .put(Items.WARPED_FUNGUS, normal(DARK, HELL, WEAK))
            .put(Items.CRIMSON_FUNGUS, normal(DARK, HELL, POWER))
            .put(Items.CRIMSON_ROOTS, normal(HELL, FIRE, POWER))
            .put(Items.WARPED_ROOTS, normal(HELL, FIRE, WEAK))
            .put(Items.NETHER_SPROUTS, normal(HELL, LANDSCAPE, FIRE))
            .put(Items.SUGAR_CANE, normal(WET, EARTH))
            .put(Items.KELP, weak(WATER, EARTH))
            .put(Items.TORCH, normal(LIGHT, HOT))
            .put(Items.END_ROD, normal(LIGHT, END))
            .put(Items.LADDER, weak(CAVE, MINE, AIR))
            .put(Items.IRON_BARS, normal(CRAFT, EARTH))
            .put(Items.CHAIN, normal(CRAFT, FIRE))
            .put(Items.VINE, normal(WET, AIR, LANDSCAPE))
            .put(Items.LILY_PAD, normal(WET, WATER, LANDSCAPE))
            .put(Items.SUNFLOWER, weak(CAVE, HOT, EARTH))
            .put(Items.LILAC, weak(FIRE, HOT, EARTH))
            .put(Items.ROSE_BUSH, weak(CAVE, LIGHT, EARTH))
            .put(Items.PEONY, weak(WEAK, WATER, LANDSCAPE))
            .put(Items.TALL_GRASS, weak(LANDSCAPE, LIGHT))
            .put(Items.LARGE_FERN, weak(LANDSCAPE, WET))
            .put(Items.TUBE_CORAL, decent(WET, COLD, WATER))
            .put(Items.BRAIN_CORAL, decent(WET, CRAFT, WATER))
            .put(Items.BUBBLE_CORAL, decent(WET, AIR, WATER))
            .put(Items.FIRE_CORAL, decent(WET, FIRE, WATER))
            .put(Items.HORN_CORAL, decent(WET, TREASURE, WATER))
            .put(Items.DEAD_TUBE_CORAL, decent(DRY, COLD))
            .put(Items.DEAD_BRAIN_CORAL, decent(DRY, CRAFT))
            .put(Items.DEAD_BUBBLE_CORAL, decent(DRY, AIR))
            .put(Items.DEAD_FIRE_CORAL, decent(DRY, FIRE))
            .put(Items.DEAD_HORN_CORAL, decent(DRY, TREASURE))
            .put(Items.TUBE_CORAL_FAN, decent(WET, COLD, WATER))
            .put(Items.BRAIN_CORAL_FAN, decent(WET, CRAFT, WATER))
            .put(Items.BUBBLE_CORAL_FAN, decent(WET, AIR, WATER))
            .put(Items.FIRE_CORAL_FAN, decent(WET, FIRE, WATER))
            .put(Items.HORN_CORAL_FAN, decent(WET, TREASURE, WATER))
            .put(Items.DEAD_TUBE_CORAL_FAN, decent(DRY, COLD))
            .put(Items.DEAD_BRAIN_CORAL_FAN, decent(DRY, CRAFT))
            .put(Items.DEAD_BUBBLE_CORAL_FAN, decent(DRY, AIR))
            .put(Items.DEAD_FIRE_CORAL_FAN, decent(DRY, FIRE))
            .put(Items.DEAD_HORN_CORAL_FAN, decent(DRY, TREASURE))
            .put(Items.ITEM_FRAME, weak(CRAFT, TREASURE))
            .put(Items.FLOWER_POT, weak(EARTH, WET))
            .put(Items.SKELETON_SKULL, ultraStrong(WEAK, TRASH, LANDSCAPE))
            .put(Items.WITHER_SKELETON_SKULL, ultraStrong(HELL, HOT, FIRE))
            .put(Items.PLAYER_HEAD, ultraStrong(LIGHT, CRAFT, AIR))
            .put(Items.ZOMBIE_HEAD, ultraStrong(EARTH, WATER, DARK))
            .put(Items.CREEPER_HEAD, ultraStrong(MINE, POWER, CAVE))
            .put(Items.DRAGON_HEAD, ultraStrong(END, COLD, TREASURE))
            .put(Items.BELL, normal(LANDSCAPE, CRAFT))
            .put(Items.SOUL_LANTERN, normal(LIGHT, DRY, EARTH))
            .put(Items.LEVER, weak(TRASH, POWER))
            .put(Items.REDSTONE_TORCH, normal(LIGHT, POWER))
            .put(Items.REPEATER, weak(POWER, CRAFT))
            .put(Items.COMPARATOR, weak(CRAFT, POWER))
            .put(Items.SADDLE, veryStrong(TREASURE, LANDSCAPE, DRY))
            .put(Items.ELYTRA, ultraStrong(AIR, END))
            .put(Items.CARROT_ON_A_STICK, normal(EARTH, LANDSCAPE))
            .put(Items.WARPED_FUNGUS_ON_A_STICK, normal(FIRE, LANDSCAPE))
            .put(Items.OAK_BOAT, weak(WET, WATER, CAVE))
            .put(Items.BIRCH_BOAT, weak(WET, WATER, TRASH))
            .put(Items.SPRUCE_BOAT, weak(WET, WATER, COLD))
            .put(Items.JUNGLE_BOAT, weak(WET, WATER, WET))
            .put(Items.ACACIA_BOAT, weak(WET, WATER, HOT))
            .put(Items.DARK_OAK_BOAT, weak(WET, WATER, DARK))
            .put(Items.BEACON, insane(LIGHT, AIR, HELL))
            .put(Items.TURTLE_EGG, decent(WATER, TREASURE, WET))
            .put(Items.SCUTE, decent(EARTH, WATER))
            .put(Items.COAL, normal(FIRE, MINE))
            .put(Items.CHARCOAL, normal(FIRE, LANDSCAPE))
            .put(Items.DIAMOND, strong(POWER, TREASURE, CAVE))
            .put(Items.GOLD_INGOT, strong(TREASURE, CAVE))
            .put(Items.IRON_INGOT, decent(POWER, CAVE))
            .put(Items.NETHERITE_INGOT, veryStrong(POWER, HELL))
            .put(Items.STICK, weak(LANDSCAPE, TRASH))
            .put(Items.BOWL, weak(TRASH, DRY))
            .put(Items.STRING, weak(CAVE))
            .put(Items.FEATHER, weak(AIR, DRY, COLD))
            .put(Items.WHEAT_SEEDS, weak(EARTH, LANDSCAPE))
            .put(Items.MELON_SEEDS, weak(EARTH, WET))
            .put(Items.PUMPKIN_SEEDS, weak(EARTH, DARK))
            .put(Items.BEETROOT_SEEDS, weak(EARTH, DRY))
            .put(Items.WHEAT, weak(EARTH, WET, LIGHT))
            .put(Items.SNOWBALL, normal(COLD, WET, WATER))
            .put(Items.LEATHER, normal(DRY, CRAFT, LANDSCAPE))
            .put(Items.BRICK, normal(DRY, CRAFT, FIRE))
            .put(Items.CLAY_BALL, weak(WET, MINE, LANDSCAPE))
            .put(Items.PAPER, weak(CRAFT, DRY))
            .put(Items.BOOK, normal(TREASURE, CRAFT, DRY))
            .put(Items.SLIME_BALL, strong(WET, TREASURE, CAVE))
            .put(Items.EGG, decent(LANDSCAPE, LIGHT, TREASURE))
            .put(Items.COCOA_BEANS, decent(TREASURE, LANDSCAPE))
            .put(Items.LAPIS_LAZULI, weak(MINE, WATER, CAVE))
            .put(Items.BONE_MEAL, weak(DARK, TRASH, POWER))
            .put(Items.BONE, normal(DARK, TRASH, POWER))
            .put(Items.WHITE_DYE, normal(CRAFT, LIGHT))
            .put(Items.ORANGE_DYE, normal(CRAFT, HOT))
            .put(Items.MAGENTA_DYE, normal(CRAFT, CAVE))
            .put(Items.LIGHT_BLUE_DYE, normal(CRAFT, AIR))
            .put(Items.YELLOW_DYE, normal(CRAFT, TREASURE))
            .put(Items.LIME_DYE, normal(CRAFT, LANDSCAPE))
            .put(Items.PINK_DYE, normal(CRAFT, HELL))
            .put(Items.GRAY_DYE, normal(CRAFT, DRY))
            .put(Items.LIGHT_GRAY_DYE, normal(CRAFT, WEAK))
            .put(Items.CYAN_DYE, normal(CRAFT, COLD))
            .put(Items.PURPLE_DYE, normal(CRAFT, END))
            .put(Items.BLUE_DYE, normal(CRAFT, WATER))
            .put(Items.BROWN_DYE, normal(CRAFT, WET))
            .put(Items.GREEN_DYE, normal(CRAFT, EARTH))
            .put(Items.RED_DYE, normal(CRAFT, FIRE))
            .put(Items.BLACK_DYE, normal(CRAFT, DARK))
            .put(Items.BLAZE_ROD, decent(HELL, FIRE, HOT))
            .put(Items.GOLD_NUGGET, normal(TREASURE, CAVE))
            .put(Items.IRON_NUGGET, weak(POWER, CAVE))
            .put(Items.EXPERIENCE_BOTTLE, strong(TREASURE, POWER, CRAFT))
            .put(Items.FIRE_CHARGE, normal(FIRE, HELL))
            .put(Items.WRITABLE_BOOK, normal(CRAFT, DRY))
            .put(Items.FIREWORK_ROCKET, decent(AIR, FIRE))
            .put(Items.FIREWORK_STAR, normal(FIRE, AIR))
            .put(Items.NETHER_BRICK, weak(HELL, DRY, FIRE))
            .put(Items.PRISMARINE_SHARD, decent(WATER, WET))
            .put(Items.RABBIT_HIDE, normal(DRY, LANDSCAPE))
            .put(Items.LEATHER_HORSE_ARMOR, weak(CRAFT, DRY, WEAK))
            .put(Items.IRON_HORSE_ARMOR, veryStrong(POWER, CAVE))
            .put(Items.GOLDEN_HORSE_ARMOR, veryStrong(TREASURE, CAVE))
            .put(Items.DIAMOND_HORSE_ARMOR, veryStrong(POWER, TREASURE, CAVE))
            .put(Items.CHORUS_FRUIT, normal(END, AIR, LANDSCAPE))
            .put(Items.POPPED_CHORUS_FRUIT, decent(END, AIR))
            .put(Items.MUSIC_DISC_13, veryStrong(CAVE))
            .put(Items.MUSIC_DISC_CAT, veryStrong(TREASURE))
            .put(Items.MUSIC_DISC_BLOCKS, veryStrong(LANDSCAPE))
            .put(Items.MUSIC_DISC_CHIRP, veryStrong(COLD))
            .put(Items.MUSIC_DISC_FAR, veryStrong(END))
            .put(Items.MUSIC_DISC_MALL, veryStrong(WEAK))
            .put(Items.MUSIC_DISC_MELLOHI, veryStrong(POWER))
            .put(Items.MUSIC_DISC_STAL, veryStrong(DARK))
            .put(Items.MUSIC_DISC_STRAD, veryStrong(LIGHT))
            .put(Items.MUSIC_DISC_WARD, veryStrong(DRY))
            .put(Items.MUSIC_DISC_11, veryStrong(TRASH))
            .put(Items.MUSIC_DISC_WAIT, veryStrong(WET))
            .put(Items.MUSIC_DISC_PIGSTEP, veryStrong(HELL))
            .put(Items.NAUTILUS_SHELL, strong(TREASURE, WATER))
            .put(Items.HEART_OF_THE_SEA, veryStrong(WATER, TREASURE, WET))
            .put(Items.HONEYCOMB, decent(LANDSCAPE, DRY, HOT))
            .put(Items.APPLE, normal(LANDSCAPE, AIR))
            .put(Items.MUSHROOM_STEW, normal(DARK, LANDSCAPE))
            .put(Items.PORKCHOP, normal(WEAK, LANDSCAPE, EARTH))
            .put(Items.COOKED_PORKCHOP, normal(HOT, LANDSCAPE, EARTH))
            .put(Items.BEEF, normal(WEAK, WET, EARTH))
            .put(Items.COOKED_BEEF, normal(HOT, WET, EARTH))
            .put(Items.CHICKEN, normal(WEAK, TRASH, EARTH))
            .put(Items.COOKED_CHICKEN, normal(HOT, TRASH, EARTH))
            .put(Items.RABBIT, normal(WEAK, DRY, EARTH))
            .put(Items.COOKED_RABBIT, normal(HOT, DRY, EARTH))
            .put(Items.MUTTON, normal(WEAK, CAVE, EARTH))
            .put(Items.COOKED_MUTTON, normal(HOT, CAVE, EARTH))
            .put(Items.COD, normal(WEAK, DARK, WATER))
            .put(Items.COOKED_COD, normal(HOT, DARK, WATER))
            .put(Items.SALMON, normal(WEAK, AIR, WATER))
            .put(Items.COOKED_SALMON, normal(HOT, AIR, WATER))
            .put(Items.ENCHANTED_GOLDEN_APPLE, insane(POWER, TREASURE, MINE))
            .put(Items.COOKIE, normal(LANDSCAPE, LIGHT))
            .put(Items.MELON_SLICE, normal(WET, TREASURE))
            .put(Items.DRIED_KELP, weak(WATER, TRASH))
            .put(Items.CARROT, normal(LIGHT, TREASURE, WEAK))
            .put(Items.POTATO, normal(LIGHT, TREASURE, POWER))
            .put(Items.BAKED_POTATO, normal(HOT, LIGHT))
            .put(Items.RABBIT_STEW, decent(CRAFT, HOT, DRY))
            .put(Items.BEETROOT, weak(LIGHT, WET))
            .put(Items.BEETROOT_SOUP, normal(LIGHT, WET))
            .put(Items.SWEET_BERRIES, normal(POWER, EARTH))
            .put(Items.HONEY_BOTTLE, decent(LANDSCAPE, WET, HOT))
            .put(Items.FLINT_AND_STEEL, normal(FIRE, HOT))
            .put(Items.COMPASS, strong(LANDSCAPE, CRAFT))
            .put(Items.CLOCK, strong(MINE, CAVE))
            .put(Items.FISHING_ROD, weak(CAVE, FIRE, TRASH))
            .put(Items.LEAD, strong(LANDSCAPE, LIGHT))
            .put(Items.NAME_TAG, ultraStrong(CRAFT, TREASURE))
            .put(Items.ARROW, weak(POWER, TRASH, CAVE))
            .put(Items.TRIDENT, ultraStrong(WATER, TREASURE, WET))
            .build();
}
